# Generated by Django 5.0.14 on 2026-04-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='Слаг')),
                ('color', models.CharField(choices=[('blue', 'Синий (Охрана труда)'), ('red', 'Красный (Пожбез)'), ('orange', 'Оранжевый (Промбез)'), ('green', 'Зелёный (Экология)'), ('purple', 'Фиолетовый (АРМ)'), ('gray', 'Серый (ГО)'), ('indigo', 'Индиго (Вопрос-ответ)')], default='blue', max_length=20, verbose_name='Цвет')),
                ('icon', models.CharField(blank=True, default='📋', max_length=10, verbose_name='Иконка (emoji)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', 'Статья'), ('instruction', 'Инструкция'), ('document', 'Документ'), ('video', 'Видео'), ('webinar', 'Вебинар'), ('event', 'Событие'), ('product', 'Товар/Услуга')], default='article', max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True, verbose_name='Слаг')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео (YouTube)')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/files/', verbose_name='Файл')),
                ('file_title', models.CharField(blank=True, max_length=300, verbose_name='Название файла')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_featured', models.BooleanField(default=False, verbose_name='В избранном')),
                ('is_main_slider', models.BooleanField(default=False, verbose_name='В главном слайдере')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата события')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Теги')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='content.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
