# Generated by Django 5.0.14 on 2026-04-17 05:45

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('blue', 'Синий (Охрана труда)'), ('red', 'Красный (Пожарная безопасность)'), ('orange', 'Оранжевый (Промышленная безопасность)'), ('green', 'Зеленый (Экология)'), ('purple', 'Фиолетовый (АРМ)'), ('gray', 'Серый (ГО)'), ('indigo', 'Индиго (Вопрос-ответ)')], default='blue', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('article', 'Статья'), ('instruction', 'Инструкция'), ('document', 'Документ'), ('video', 'Видео'), ('webinar', 'Вебинар'), ('event', 'Событие'), ('product', 'Товар/услуга')], default='article', max_length=20, verbose_name='Тип'),
        ),
    ]
