# Generated by Django 5.0.14 on 2026-04-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_category_color_alter_contentitem_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок баннера')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок / CTA')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 900×120 px (горизонтальный прямоугольник).', null=True, upload_to='uploads/banners/', verbose_name='Картинка баннера')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(blank=True, help_text='Оставьте пустым — баннер будет глобальным (показывается везде).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='content.category', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
