# Generated by Django 5.0.14 on 2026-04-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('header', 'Шапка сайта (правый блок)'), ('section', 'Блок раздела на главной')], default='section', max_length=20, verbose_name='Место размещения'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Для баннера в шапке — оставьте пустым. Для баннера раздела — выберите раздел.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='content.category', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Шапка: рекомендуемый размер 520×80 px. Раздел: 900×100 px.', null=True, upload_to='uploads/banners/', verbose_name='Картинка баннера'),
        ),
    ]
