# Generated by Django 5.0.14 on 2026-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_banner_placement_alter_banner_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, max_length=1024, unique=True, verbose_name='Старый путь')),
                ('new_path', models.CharField(max_length=1024, verbose_name='Новый путь')),
            ],
            options={
                'verbose_name': 'Legacy redirect',
                'verbose_name_plural': 'Legacy redirects',
                'ordering': ['old_path'],
            },
        ),
    ]
