# Generated by Django 5.2.13 on 2026-04-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_category_hierarchy_and_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Для баннера в шапке оставьте поле пустым. Для баннера раздела выберите раздел.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='content.category', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Шапка: рекомендуемый размер 520x80 px. Раздел: 900x100 px.', null=True, upload_to='uploads/banners/', verbose_name='Картинка баннера'),
        ),
    ]
