# Generated by Django 5.2.13 on 2026-04-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_banner_category_alter_banner_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'published_date'], name='content_con_status_68fadd_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'category', 'published_date'], name='content_con_status_3fab80_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'content_type', 'published_date'], name='content_con_status_b7394d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'is_main_slider', 'published_date'], name='content_con_status_c3845e_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'is_featured', 'published_date'], name='content_con_status_6d214d_idx'),
        ),
    ]
