# Generated by Django 5.2.13 on 2026-04-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_contentitem_content_con_status_68fadd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFeedBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блока')),
                ('placement', models.CharField(choices=[('home', 'Главная страница'), ('section', 'Страница раздела')], default='home', max_length=20, verbose_name='Где показывать')),
                ('title', models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название категории в заголовке.', max_length=200, verbose_name='Заголовок блока')),
                ('link_text', models.CharField(blank=True, default='Все материалы', max_length=100, verbose_name='Текст ссылки')),
                ('content_types', models.CharField(blank=True, help_text='Внутреннее поле. Выбирается через список в админке.', max_length=200, verbose_name='Типы материалов')),
                ('include_child_categories', models.BooleanField(default=True, help_text='Если включено, в блок попадут материалы из выбранной категории и всех её дочерних разделов.', verbose_name='Включать подкатегории')),
                ('item_limit', models.PositiveSmallIntegerField(default=8, help_text='Общее количество материалов в блоке, включая главный материал.', verbose_name='Количество материалов')),
                ('exclude_main_slider_items', models.BooleanField(default=True, help_text='Полезно для главной страницы, чтобы один и тот же материал не повторялся в разных блоках.', verbose_name='Не брать материалы главного слайдера')),
                ('hide_if_empty', models.BooleanField(default=True, help_text='Если подходящих материалов нет, блок не будет показан.', verbose_name='Скрывать пустой блок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('display_category', models.ForeignKey(blank=True, help_text='Необязательно. Если указать, её название, цвет и иконка будут использованы в оформлении блока.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_feed_blocks', to='content.category', verbose_name='Категория в заголовке')),
                ('source_category', models.ForeignKey(blank=True, help_text='Из этой категории будут подбираться материалы для блока.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_feed_blocks', to='content.category', verbose_name='Категория-источник')),
                ('target_category', models.ForeignKey(blank=True, help_text='Для блока на странице раздела выберите раздел, внутри которого этот блок должен отображаться.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_feed_blocks', to='content.category', verbose_name='Раздел показа')),
            ],
            options={
                'verbose_name': 'Блок вывода материалов',
                'verbose_name_plural': 'Блоки вывода материалов',
                'ordering': ['placement', 'sort_order', 'id'],
            },
        ),
    ]
