# Generated by Django 5.2.13 on 2026-04-18 13:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_contentfeedblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Служебный слаг')),
                ('public_slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Публичный URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('heading', models.CharField(blank=True, max_length=255, verbose_name='Заголовок страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/catalog/categories/', verbose_name='Изображение')),
                ('legacy_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID в старой базе')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Изменено')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.catalogcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория каталога',
                'verbose_name_plural': 'Категории каталога',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True, verbose_name='Служебный слаг')),
                ('public_slug', models.SlugField(allow_unicode=True, max_length=500, verbose_name='Публичный URL')),
                ('excerpt', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/catalog/items/', verbose_name='Основное изображение')),
                ('sku', models.CharField(blank=True, max_length=120, verbose_name='Артикул')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Спеццена')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('postcode', models.CharField(blank=True, max_length=30, verbose_name='Индекс')),
                ('phone', models.CharField(blank=True, max_length=120, verbose_name='Телефон')),
                ('mobile', models.CharField(blank=True, max_length=120, verbose_name='Мобильный')),
                ('fax', models.CharField(blank=True, max_length=120, verbose_name='Факс')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('legacy_id', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='ID в старой базе')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Изменено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.catalogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция каталога',
                'verbose_name_plural': 'Позиции каталога',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/catalog/files/', verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Скачивания')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.catalogitem', verbose_name='Позиция каталога')),
            ],
            options={
                'verbose_name': 'Файл позиции каталога',
                'verbose_name_plural': 'Файлы позиций каталога',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/catalog/items/gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.catalogitem', verbose_name='Позиция каталога')),
            ],
            options={
                'verbose_name': 'Изображение позиции каталога',
                'verbose_name_plural': 'Изображения позиций каталога',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['category', 'public_slug'], name='content_cat_categor_019e69_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['is_active', 'views'], name='content_cat_is_acti_a1bb9f_idx'),
        ),
    ]
