# Generated by Django 5.2.13 on 2026-04-18 16:22

from django.db import migrations, models


def create_home_slider_block(apps, schema_editor):
    ContentFeedBlock = apps.get_model('content', 'ContentFeedBlock')
    ContentFeedBlock.objects.get_or_create(
        placement='home_slider',
        name='Главный слайдер',
        defaults={
            'item_limit': 4,
            'secondary_item_limit': 4,
            'exclude_main_slider_items': True,
            'hide_if_empty': False,
            'is_active': True,
            'sort_order': 0,
        },
    )


def remove_home_slider_block(apps, schema_editor):
    ContentFeedBlock = apps.get_model('content', 'ContentFeedBlock')
    ContentFeedBlock.objects.filter(
        placement='home_slider',
        name='Главный слайдер',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_catalogcategory_catalogitem_catalogitemfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentfeedblock',
            name='secondary_item_limit',
            field=models.PositiveSmallIntegerField(default=4, help_text='Используется только для блока "Главный слайдер" на главной странице.', verbose_name='Количество карточек "Другие новости"'),
        ),
        migrations.AlterField(
            model_name='contentfeedblock',
            name='placement',
            field=models.CharField(choices=[('home', 'Главная страница'), ('section', 'Страница раздела'), ('home_slider', 'Главный слайдер')], default='home', max_length=20, verbose_name='Где показывать'),
        ),
        migrations.RunPython(create_home_slider_block, remove_home_slider_block),
    ]
