# Generated by Django 5.2.13 on 2026-04-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_leadsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Настройки SMTP', max_length=120, verbose_name='Название')),
                ('host', models.CharField(max_length=255, verbose_name='SMTP хост')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP порт')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Пароль')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Использовать TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Использовать SSL')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Настройки SMTP',
                'verbose_name_plural': 'Настройки SMTP',
            },
        ),
    ]
