# Generated by Django 5.2.15 on 2026-06-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_sectionbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Шапка: 520x80 px. Раздел: 900x100 px. Сайдбар статьи: ~680px по ширине (горизонтальный баннер).', null=True, upload_to='uploads/banners/', verbose_name='Картинка баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('header', 'Шапка сайта (правый блок)'), ('section', 'Блок раздела на главной'), ('sidebar', 'Сайдбар статьи (sticky)')], default='section', max_length=20, verbose_name='Место размещения'),
        ),
    ]
