# Generated by Django 5.2.15 on 2026-06-18 20:38

from django.db import migrations, models


YANDEX_METRIKA_INFORMER = """<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=988565&amp;from=informer" target="_blank" rel="nofollow">
    <img src="https://informer.yandex.ru/informer/988565/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
         style="width:88px; height:31px; border:0;"
         alt="Яндекс.Метрика"
         title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)"
        class="ym-advanced-informer" data-cid="988565" data-lang="ru"/>
</a>
<!-- /Yandex.Metrika informer -->"""


YANDEX_METRIKA_COUNTER = """<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function(m,e,t,r,i,k,a){
        m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();
        for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
        k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)
    })(window, document,'script','https://mc.yandex.ru/metrika/tag.js', 'ym');

    ym(988565, 'init', {webvisor:true, clickmap:true, referrer: document.referrer, url: location.href, accurateTrackBounce:true, trackLinks:true});
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/988565" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->"""


def create_yandex_metrika(apps, schema_editor):
    SiteCounter = apps.get_model('content', 'SiteCounter')
    SiteCounter.objects.update_or_create(
        title='Яндекс.Метрика 988565',
        defaults={
            'informer_code': YANDEX_METRIKA_INFORMER,
            'counter_code': YANDEX_METRIKA_COUNTER,
            'sort_order': 0,
            'is_active': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_banner_image_alter_banner_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Яндекс.Метрика', max_length=120, verbose_name='Название')),
                ('informer_code', models.TextField(blank=True, verbose_name='Код информера')),
                ('counter_code', models.TextField(blank=True, verbose_name='Код счетчика')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Счетчик сайта',
                'verbose_name_plural': 'Счетчики сайта',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.RunPython(create_yandex_metrika, migrations.RunPython.noop),
    ]
