#
# Nginx custom snippet for of.by.
# Ensures static/media are served directly.
#

location /static/ {
    alias /home/django/webapps/ofby/staticfiles/;
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
}

location /media/ {
    alias /home/django/webapps/ofby/media/;
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
}
